version: '3.8'

networks:
  materiaal-network:
    driver: bridge

services:
  materiaal-uitslag-web-dev:
    build: .
    container_name: materiaal-uitslag-web-dev
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
    restart: unless-stopped
    volumes:
      - .:/app  # Mount source code for development
    networks:
      - materiaal-network

