name: Build and Publish Docker image to GHCR

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate tags
        id: tags
        run: |
          DATE_TAG=$(date +%Y.%m.%d)
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT
      - name: Build Docker image (no push)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/blankf/materiaal-calc:latest
            ghcr.io/blankf/materiaal-calc:${{ steps.tags.outputs.date_tag }}
          platforms: linux/amd64,linux/arm64
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ steps.build.outputs.imageid }}
          format: table
          exit-code: 1
          ignore-unfixed: true
      - name: Push Docker image (only if scan passes)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/blankf/materiaal-calc:latest
            ghcr.io/blankf/materiaal-calc:${{ steps.tags.outputs.date_tag }}
          platforms: linux/amd64,linux/arm64
      - name: Image digest
        run: |
          echo "Image pushed: ghcr.io/${{ github.repository_owner }}/materiaal-calc:latest"